"""Rule-based inference utilities with optional OpenAI integration."""
from __future__ import annotations

from dataclasses import dataclass
import re
import textwrap
from typing import Iterable

from ..core.config import get_settings
from ..models.documents import DocumentDefinition, DocumentUsageMetrics, SectionSimplification


def _usage_from_payload(payload: dict[str, int] | None) -> DocumentUsageMetrics:
    prompt = int(payload.get("prompt_tokens", 0)) if payload else 0
    completion = int(payload.get("completion_tokens", 0)) if payload else 0
    total_value = payload.get("total_tokens") if payload else None
    total = int(total_value) if total_value is not None else prompt + completion
    return DocumentUsageMetrics(
        prompt_tokens=prompt,
        completion_tokens=completion,
        total_tokens=total,
    )


def _zero_usage() -> DocumentUsageMetrics:
    return DocumentUsageMetrics()
from .indexing import RetrievedChunk
from .ingestion import DocumentSection
from .openai_client import OpenAIClientError, get_openai_client


@dataclass(slots=True)
class QaAnswer:
    """Representation of an answer generated by the pseudo-RAG layer."""

    content: str
    sources: list[str]


def _should_use_cloud(use_cloud: bool | None) -> bool:
    if use_cloud is not None:
        return use_cloud
    return get_settings().enable_cloud_llm


def _build_summary_local(text: str) -> str:
    paragraphs = [paragraph.strip() for paragraph in text.splitlines() if paragraph.strip()]
    if not paragraphs:
        return "Brak treści do podsumowania."
    first = paragraphs[0]
    if len(first) > 280:
        first = first[:277] + "..."
    return first


def _has_meaningful_text(text: str) -> bool:
    return bool(text and text.strip())


def build_summary(text: str, use_cloud: bool | None = None) -> tuple[str, DocumentUsageMetrics]:
    """Return a short summary, preferring OpenAI when available."""

    if not _has_meaningful_text(text):
        return _build_summary_local(text), _zero_usage()

    if _should_use_cloud(use_cloud):
        client = get_openai_client()
        try:
            summary, usage = client.summarise(text)
            if summary:
                return summary, _usage_from_payload(usage)
        except OpenAIClientError:
            pass
    return _build_summary_local(text), _zero_usage()


def _collect_sentences(text: str, keywords: Iterable[str]) -> list[str]:
    sentences: list[str] = []
    for sentence in textwrap.dedent(text).split('.'):
        normalised = sentence.strip()
        if not normalised:
            continue
        lowered = normalised.lower()
        if any(keyword in lowered for keyword in keywords):
            sentences.append(normalised + '.')
    return sentences


def extract_obligations(text: str, use_cloud: bool | None = None) -> tuple[list[str], DocumentUsageMetrics]:
    if not _has_meaningful_text(text):
        return [], _zero_usage()

    if _should_use_cloud(use_cloud):
        client = get_openai_client()
        try:
            obligations, usage = client.extract_items(text, "obowiązki")
            if obligations:
                return obligations, _usage_from_payload(usage)
        except OpenAIClientError:
            pass
    return _collect_sentences(text, ["zobowiąz", "obowiąz", "należy"]), _zero_usage()


def extract_penalties(text: str, use_cloud: bool | None = None) -> tuple[list[str], DocumentUsageMetrics]:
    if not _has_meaningful_text(text):
        return [], _zero_usage()

    if _should_use_cloud(use_cloud):
        client = get_openai_client()
        try:
            penalties, usage = client.extract_items(text, "kary lub sankcje")
            if penalties:
                return penalties, _usage_from_payload(usage)
        except OpenAIClientError:
            pass
    return _collect_sentences(text, ["kara", "odpowiedzialn", "grzywna"]), _zero_usage()


def extract_deadlines(text: str, use_cloud: bool | None = None) -> tuple[list[str], DocumentUsageMetrics]:
    if not _has_meaningful_text(text):
        return [], _zero_usage()

    if _should_use_cloud(use_cloud):
        client = get_openai_client()
        try:
            deadlines, usage = client.extract_items(text, "terminy lub daty graniczne")
            if deadlines:
                return deadlines, _usage_from_payload(usage)
        except OpenAIClientError:
            pass
    return _collect_sentences(text, ["termin", "dni", "miesiąc", "miesiac"]), _zero_usage()


def extract_risks(text: str, use_cloud: bool | None = None) -> tuple[list[str], DocumentUsageMetrics]:
    if not _has_meaningful_text(text):
        return [], _zero_usage()

    if _should_use_cloud(use_cloud):
        client = get_openai_client()
        try:
            risks, usage = client.extract_items(text, "ryzyka dla stron umowy")
            if risks:
                return risks, _usage_from_payload(usage)
        except OpenAIClientError:
            pass
    return _collect_sentences(text, ["ryzyk", "zagroż", "niebezpiecz", "utrata", "szkody"]), _zero_usage()


def answer_question(
    question: str, retrieved_chunks: list[RetrievedChunk], use_cloud: bool | None = None
) -> QaAnswer:
    if _should_use_cloud(use_cloud):
        client = get_openai_client()
        try:
            result, _usage = client.answer_question(question, retrieved_chunks)
            content = str(result.get("answer", "")).strip()
            if content:
                sources = [str(source) for source in result.get("sources", []) if str(source).strip()]
                return QaAnswer(content=content, sources=sources)
        except OpenAIClientError:
            pass
    return _answer_question_local(question, retrieved_chunks)


def _answer_question_local(question: str, retrieved_chunks: list[RetrievedChunk]) -> QaAnswer:
    if not retrieved_chunks:
        return QaAnswer(content="Brak danych pozwalających na udzielenie odpowiedzi.", sources=[])
    best = retrieved_chunks[0]
    summary = _build_summary_local(best.text)
    content = (
        f"Na podstawie sekcji '{best.identifier}' odpowiedź brzmi: {summary} "
        "(odpowiedź wygenerowana heurystycznie)."
    )
    sources = [chunk.identifier for chunk in retrieved_chunks]
    return QaAnswer(content=content, sources=sources)


_SENTENCE_SPLIT = re.compile(r"(?<=[.!?])\s+")
_AMOUNT_PATTERN = re.compile(r"(\d[\d\s\u00a0]*)(?:\s*)(zł|pln)", re.IGNORECASE)
_DEADLINE_PATTERN = re.compile(r"(\d+[\s\u00a0]*)(dni|dzień|dnia|miesi(?:ą|a)c)", re.IGNORECASE)
_DEFINITION_VERB_PATTERN = re.compile(
    r"[„\"']?(?P<term>[A-ZŁŚŻŹĆÓ][^\"”'\n]{1,80}?)[”\"']?\s+"
    r"(?:oznacza|zwan[ayoe]?|zwanych|zwanym|rozumie się jako|należy rozumieć jako)\s+"
    r"(?P<definition>[^.;]+)",
    re.IGNORECASE,
)
_REPLACEMENTS: tuple[tuple[re.Pattern[str], str], ...] = (
    (re.compile(r"\bNiniejszym\b", re.IGNORECASE), "Tym dokumentem"),
    (re.compile(r"\bNiniejsza\b", re.IGNORECASE), "Ta"),
    (re.compile(r"\bNiniejszy\b", re.IGNORECASE), "Ten"),
    (re.compile(r"\bStrony\b", re.IGNORECASE), "osoby"),
    (re.compile(r"\bStrona\b", re.IGNORECASE), "osoba"),
    (re.compile(r"\bjest zobowiązan[ay]\b(?:\s+do)?", re.IGNORECASE), "musi"),
    (re.compile(r"\bzobowiązan[ey]\b", re.IGNORECASE), "ma obowiązek"),
    (re.compile(r"\bNależy\b", re.IGNORECASE), "Trzeba"),
    (re.compile(r"\bPowinien\b", re.IGNORECASE), "Powinieneś"),
    (re.compile(r"\bW terminie\b", re.IGNORECASE), "W ciągu"),
    (re.compile(r"\bKara umowna\b", re.IGNORECASE), "Kara"),
    (re.compile(r"\bArt\.\s*(\d+)\b", re.IGNORECASE), r"Artykuł \1"),
    (re.compile(r"§"), "paragraf"),
)


def simplify_sections(
    sections: Iterable[DocumentSection], use_cloud: bool | None = None
) -> tuple[list[SectionSimplification], DocumentUsageMetrics]:
    """Generate plain-language explanations using OpenAI when enabled."""

    section_list = list(sections)
    if not any(_has_meaningful_text(section.text) for section in section_list):
        return [], _zero_usage()
    if _should_use_cloud(use_cloud):
        client = get_openai_client()
        try:
            ai_results, usage = client.simplify_sections(section_list)
            mapped = {section.identifier: section for section in section_list}
            simplifications: list[SectionSimplification] = []
            for item in ai_results:
                identifier = item.get("identifier")
                if not identifier:
                    continue
                identifier = str(identifier)
                source_section = mapped.get(identifier)
                source_text = source_section.text if source_section else ""
                excerpt_raw = item.get("source_excerpt")
                excerpt = str(excerpt_raw) if excerpt_raw is not None else ""
                simplifications.append(
                    SectionSimplification(
                        identifier=identifier,
                        source_excerpt=(excerpt or _create_excerpt(source_text)),
                        source_text=source_text,
                        plain_language=str(item.get("plain_language", "")),
                    )
                )
            if simplifications:
                return simplifications, _usage_from_payload(usage)
        except OpenAIClientError:
            pass
    return _simplify_sections_local(section_list), _zero_usage()


def _simplify_sections_local(sections: Iterable[DocumentSection]) -> list[SectionSimplification]:
    simplifications: list[SectionSimplification] = []
    for section in sections:
        plain_text = _simplify_text(section.text)
        excerpt = _create_excerpt(section.text)
        simplifications.append(
            SectionSimplification(
                identifier=section.identifier,
                source_excerpt=excerpt,
                source_text=section.text,
                plain_language=plain_text,
            )
        )
    return simplifications


def _simplify_text(text: str) -> str:
    sentences = [segment.strip() for segment in _SENTENCE_SPLIT.split(text) if segment and segment.strip()]
    if not sentences:
        sentences = [text.strip()]
    simplified: list[str] = []
    for sentence in sentences:
        simplified_sentence = sentence
        for pattern, replacement in _REPLACEMENTS:
            simplified_sentence = pattern.sub(replacement, simplified_sentence)
        simplified_sentence = re.sub(r"\s+", " ", simplified_sentence).strip()
        if not simplified_sentence:
            continue
        simplified_sentence = simplified_sentence[0].upper() + simplified_sentence[1:]
        if simplified_sentence[-1] not in ".!?":
            simplified_sentence += "."
        simplified.append(simplified_sentence)
    insights = _derive_insights(text)
    if insights:
        simplified.append("Ważne informacje: " + " ".join(insights))
    content = " ".join(simplified)
    if not content:
        content = "Tekst nie zawiera szczegółów do uproszczenia."
    return f"W prostych słowach: {content}"


def _derive_insights(text: str) -> list[str]:
    insights: list[str] = []
    seen: set[str] = set()
    for match in _DEADLINE_PATTERN.finditer(text):
        value = f"Masz {match.group(1).strip()} {match.group(2).lower()} na wykonanie zadania."
        if value not in seen:
            seen.add(value)
            insights.append(value)
    for match in _AMOUNT_PATTERN.finditer(text):
        amount = f"Kwota to {match.group(1).strip()} {match.group(2).upper()}."
        if amount not in seen:
            seen.add(amount)
            insights.append(amount)
    return insights


def _create_excerpt(text: str) -> str:
    collapsed = re.sub(r"\s+", " ", text).strip()
    if len(collapsed) <= 280:
        return collapsed
    return collapsed[:277] + "..."


def extract_definitions(text: str) -> list[DocumentDefinition]:
    """Derive a glossary of legal terms from sanitised text."""

    definitions: dict[str, DocumentDefinition] = {}
    for sentence in _iter_definition_candidates(text):
        for term, meaning in _parse_definition_sentence(sentence):
            if not term or not meaning:
                continue
            key = term.lower()
            if key in definitions:
                continue
            definitions[key] = DocumentDefinition(
                term=term,
                meaning=meaning,
                source=sentence.strip(),
            )
    return list(definitions.values())


def _iter_definition_candidates(text: str) -> Iterable[str]:
    for raw_line in text.splitlines():
        stripped = raw_line.strip()
        if not stripped:
            continue
        # Process both raw lines and sentence-level splits to capture multi-line definitions.
        yield stripped
        for sentence in _SENTENCE_SPLIT.split(stripped):
            sentence = sentence.strip()
            if sentence and sentence != stripped:
                yield sentence


def _parse_definition_sentence(sentence: str) -> Iterable[tuple[str, str]]:
    matches = []
    verb_match = _DEFINITION_VERB_PATTERN.search(sentence)
    if verb_match:
        matches.append(
            (
                _normalise_term(verb_match.group("term")),
                _clean_meaning(verb_match.group("definition")),
            )
        )
    separator_match = _split_definition_by_separator(sentence)
    if separator_match:
        matches.append(separator_match)
    for term, meaning in matches:
        term = term.strip()
        meaning = meaning.strip()
        if len(term) > 1 and len(meaning) > 3:
            yield term, meaning


def _split_definition_by_separator(sentence: str) -> tuple[str, str] | None:
    # Support patterns such as "Klient – osoba fizyczna ..." or "Klient: osoba ..."
    separator: str | None = None
    for token in (" – ", " - ", " — ", ":", " –", "-", "—"):
        if token in sentence:
            separator = token
            break
    if not separator:
        return None
    parts = sentence.split(separator, 1)
    if len(parts) != 2:
        return None
    term, definition = parts[0].strip(), parts[1].strip()
    if len(term.split()) > 6:
        return None
    if not term or not definition:
        return None
    return _normalise_term(term), _clean_meaning(definition)


def _normalise_term(term: str) -> str:
    cleaned = term.strip().strip("'\"”„“»«")
    cleaned = re.sub(r"\s+", " ", cleaned)
    return cleaned


def _clean_meaning(meaning: str) -> str:
    cleaned = meaning.strip().rstrip(".;")
    cleaned = re.sub(r"\s+", " ", cleaned)
    return cleaned
