"""Rule-based inference utilities used in lieu of the final LLM stage."""
from __future__ import annotations

from dataclasses import dataclass
import textwrap
from typing import Iterable

from .indexing import RetrievedChunk


@dataclass(slots=True)
class QaAnswer:
    """Representation of an answer generated by the pseudo-RAG layer."""

    content: str
    sources: list[str]


def build_summary(text: str) -> str:
    """Create a deterministic short summary from the sanitised text."""

    paragraphs = [paragraph.strip() for paragraph in text.splitlines() if paragraph.strip()]
    if not paragraphs:
        return "Brak treści do podsumowania."
    first = paragraphs[0]
    if len(first) > 280:
        first = first[:277] + "..."
    return first


def _collect_sentences(text: str, keywords: Iterable[str]) -> list[str]:
    sentences: list[str] = []
    for sentence in textwrap.dedent(text).split('.'):
        normalised = sentence.strip()
        if not normalised:
            continue
        lowered = normalised.lower()
        if any(keyword in lowered for keyword in keywords):
            sentences.append(normalised + '.')
    return sentences


def extract_obligations(text: str) -> list[str]:
    return _collect_sentences(text, ["zobowiąz", "obowiąz", "należy"])


def extract_penalties(text: str) -> list[str]:
    return _collect_sentences(text, ["kara", "odpowiedzialn", "grzywna"])


def extract_deadlines(text: str) -> list[str]:
    return _collect_sentences(text, ["termin", "dni", "miesiąc", "miesiac"])


def answer_question(question: str, retrieved_chunks: list[RetrievedChunk]) -> QaAnswer:
    if not retrieved_chunks:
        return QaAnswer(content="Brak danych pozwalających na udzielenie odpowiedzi.", sources=[])
    best = retrieved_chunks[0]
    summary = build_summary(best.text)
    content = (
        f"Na podstawie sekcji '{best.identifier}' odpowiedź brzmi: {summary} "
        "(odpowiedź wygenerowana heurystycznie)."
    )
    sources = [chunk.identifier for chunk in retrieved_chunks]
    return QaAnswer(content=content, sources=sources)
